# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0e38cb616e8e237643d6e1172d34a0a215ea42c5be9aa1362cec5519fff237c7c9c2787697c5249b9ee98348506e92f6dba697f5937f955023980bbc016f73

test:
  secret_key_base: f020336ce96517554b90bef8a936ccb6289fd132472b69e1bc423f85d0b411b1546aa6fe9a5a24e25189915f62ffdba2f0ab7bfbe52661255738f09393c1fb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
